name: CI
env:
  APP_NAME: fast-decompress-wasm
'on':
  push:
    branches:
      - main
      - fixCI
    tags-ignore:
      - '**'
  pull_request: null
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: Build package
        run: wasm-pack build --scope gkotulski
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./pkg/
  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts
      - name: Download wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Files
        run: ls -R
      - name: Publish
        shell: bash
        run: |
          if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            ls -R
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            wasm-pack publish
          else
            echo "Not a release, skipping publish"
          fi
        working-directory: ./artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}